#!/usr/bin/env python3
"""
Generate a Poseidon hash Circom template for BN254 with t=3 (2-input hash).

Uses the standard Grain LFSR for round constant generation and Cauchy MDS matrix,
as specified in the Poseidon paper (https://eprint.iacr.org/2019/458).

Parameters: t=3, Rf=8, Rp=57, alpha=5 (S-box x^5), BN254 scalar field.
"""

import sys

# BN254 scalar field prime
P = 21888242871839275222246405745257275088548364400416034343698204186575808495617

def modinv(a, p):
    """Modular inverse via extended Euclidean algorithm."""
    if a == 0:
        raise ValueError("no inverse for 0")
    g, x, _ = extended_gcd(a % p, p)
    if g != 1:
        raise ValueError(f"no inverse: gcd={g}")
    return x % p

def extended_gcd(a, b):
    if a == 0:
        return b, 0, 1
    g, x, y = extended_gcd(b % a, a)
    return g, y - (b // a) * x, x

# ---------- Grain LFSR for round constants ----------

def grain_lfsr_init(field_size_bits, t, Rf, Rp):
    """Initialize 80-bit Grain LFSR state for Poseidon constant generation."""
    state = []

    # 2 bits: field type (1 = prime field)
    state += [1, 0]

    # 4 bits: S-box indicator (for x^5, encode as 0b0100 reversed = [0,0,1,0])
    # Actually: 1 bit for sign (0=positive), 3 bits for value of alpha-1=4
    # alpha=5 → positive, value=4=0b100 → bits [0, 0, 0, 1, 0, 0] ...
    # Let me use the standard encoding:
    # 4 bits: exponent indicator. For x^alpha: the 4 bits encode alpha.
    # alpha=5 = 0b0101 → [1, 0, 1, 0] (LSB first)
    state += [1, 0, 1, 0]

    # 12 bits: field size n (254 for BN254), LSB first
    n = field_size_bits
    for i in range(12):
        state.append((n >> i) & 1)

    # 12 bits: t, LSB first
    for i in range(12):
        state.append((t >> i) & 1)

    # 10 bits: Rf, LSB first
    for i in range(10):
        state.append((Rf >> i) & 1)

    # 10 bits: Rp, LSB first
    for i in range(10):
        state.append((Rp >> i) & 1)

    # Remaining bits (80 - 2 - 4 - 12 - 12 - 10 - 10 = 30) set to 1
    state += [1] * 30

    assert len(state) == 80
    return state

def grain_get_bit(state):
    """Clock LFSR and return output bit."""
    # Feedback polynomial: x^80 + x^62 + x^51 + x^38 + x^23 + x^13 + 1
    new_bit = state[0] ^ state[13] ^ state[23] ^ state[38] ^ state[51] ^ state[62]
    state.pop(0)
    state.append(new_bit)
    return new_bit

def grain_get_field_element(state, n, p):
    """Generate one field element from the Grain LFSR."""
    while True:
        # Generate n bits
        bits = []
        for _ in range(n):
            # Get a valid bit (filter: only use bit if LFSR says it's valid)
            while grain_get_bit(state) == 0:
                grain_get_bit(state)  # discard
            bits.append(grain_get_bit(state))

        # Convert to integer (LSB first)
        val = sum(b * (2 ** i) for i, b in enumerate(bits))
        if val < p:
            return val

def generate_round_constants(t, Rf, Rp):
    """Generate all Poseidon round constants for BN254."""
    n = 254  # field size in bits
    state = grain_lfsr_init(n, t, Rf, Rp)

    # Discard first 160 bits (initialization)
    for _ in range(160):
        grain_get_bit(state)

    num_constants = (Rf + Rp) * t
    constants = []
    for _ in range(num_constants):
        c = grain_get_field_element(state, n, P)
        constants.append(c)

    return constants

# ---------- MDS Matrix ----------

def generate_mds_matrix(t):
    """Generate t×t Cauchy MDS matrix over BN254 scalar field."""
    # Use xs = [0, 1, ..., t-1] and ys = [t, t+1, ..., 2t-1]
    xs = list(range(t))
    ys = list(range(t, 2 * t))

    M = []
    for i in range(t):
        row = []
        for j in range(t):
            val = modinv((xs[i] + ys[j]) % P, P)
            row.append(val)
        M.append(row)
    return M

# ---------- Circom Generation ----------

def generate_circom(t, Rf, Rp, output_file=None):
    """Generate complete Poseidon Circom template."""
    nInputs = t - 1  # capacity = 1
    nRounds = Rf + Rp
    half_Rf = Rf // 2

    print(f"Generating Poseidon for BN254: t={t}, Rf={Rf}, Rp={Rp}, nRounds={nRounds}")
    print(f"  Round constants: {nRounds * t}")
    print(f"  MDS matrix: {t}x{t}")

    C = generate_round_constants(t, Rf, Rp)
    M = generate_mds_matrix(t)

    print(f"  Generated {len(C)} round constants")
    print(f"  MDS[0][0] = {M[0][0]}")

    lines = []
    w = lines.append

    w('pragma circom 2.0.0;')
    w('')
    w('// =============================================================')
    w(f'// Poseidon Hash for BN254 (t={t}, Rf={Rf}, Rp={Rp}, alpha=5)')
    w('// Generated by gen_poseidon.py')
    w('// =============================================================')
    w('')

    # S-box template
    w('// S-box: x^5')
    w('template Sigma() {')
    w('    signal input in;')
    w('    signal output out;')
    w('    signal in2;')
    w('    signal in4;')
    w('    in2 <== in * in;')
    w('    in4 <== in2 * in2;')
    w('    out <== in4 * in;')
    w('}')
    w('')

    # Main Poseidon template
    w(f'template Poseidon{nInputs}() {{')
    w(f'    signal private input in[{nInputs}];')
    w(f'    signal output out;')
    w('')
    w(f'    var t = {t};')
    w(f'    var nRoundsF = {Rf};')
    w(f'    var nRoundsP = {Rp};')
    w(f'    var nRounds = {nRounds};')
    w('')

    # Emit MDS constants as signals
    w(f'    // MDS matrix constants ({t}x{t} = {t*t} signals)')
    for i in range(t):
        for j in range(t):
            w(f'    signal mds_{i}_{j};')
    for i in range(t):
        for j in range(t):
            w(f'    mds_{i}_{j} <== {M[i][j]};')
    w('')

    # State signals: state_r{round}_{element}
    # We use explicit signal names to avoid nested array issues
    w(f'    // Initial state')
    w(f'    signal state_0_0;')
    w(f'    state_0_0 <== 0;')
    for i in range(nInputs):
        w(f'    signal state_0_{i+1};')
        w(f'    state_0_{i+1} <== in[{i}];')
    w('')

    # Process rounds
    for r in range(nRounds):
        w(f'    // === Round {r} {"(full)" if r < half_Rf or r >= half_Rf + Rp else "(partial)"} ===')

        # Step 1: Add round constants
        for i in range(t):
            ci = r * t + i
            w(f'    signal rc_{r}_{i};')
            w(f'    rc_{r}_{i} <== {C[ci]};')
        w('')

        for i in range(t):
            w(f'    signal ark_{r}_{i};')
            w(f'    ark_{r}_{i} <== state_{r}_{i} + rc_{r}_{i};')
        w('')

        # Step 2: S-box
        is_full_round = (r < half_Rf) or (r >= half_Rf + Rp)
        if is_full_round:
            # Full round: S-box on all elements
            for i in range(t):
                w(f'    component sbox_{r}_{i} = Sigma();')
                w(f'    sbox_{r}_{i}.in <== ark_{r}_{i};')
            w('')
            sbox_out = lambda i: f'sbox_{r}_{i}.out'
        else:
            # Partial round: S-box only on first element
            w(f'    component sbox_{r}_0 = Sigma();')
            w(f'    sbox_{r}_0.in <== ark_{r}_0;')
            w('')
            sbox_out = lambda i: f'sbox_{r}_0.out' if i == 0 else f'ark_{r}_{i}'

        # Step 3: MDS mix
        # For each output: out[i] = sum_j(mds[i][j] * sbox_out[j])
        for i in range(t):
            for j in range(t):
                w(f'    signal mix_{r}_{i}_{j};')
                w(f'    mix_{r}_{i}_{j} <== mds_{i}_{j} * {sbox_out(j)};')

        w('')

        # Sum the mix terms
        next_r = r + 1
        for i in range(t):
            w(f'    signal mixsum_{r}_{i}_01;')
            w(f'    mixsum_{r}_{i}_01 <== mix_{r}_{i}_0 + mix_{r}_{i}_1;')
            w(f'    signal state_{next_r}_{i};')
            w(f'    state_{next_r}_{i} <== mixsum_{r}_{i}_01 + mix_{r}_{i}_2;')

        w('')

    # Output: first element of final state
    w(f'    out <== state_{nRounds}_1;')
    w('}')
    w('')

    # Main component
    w(f'component main = Poseidon{nInputs}();')
    w('')

    content = '\n'.join(lines)

    if output_file:
        with open(output_file, 'w') as f:
            f.write(content)
        print(f"  Written to {output_file}")

        # Count constraints
        n_sbox = half_Rf * t + (nRounds - 2 * half_Rf) * 1  # S-boxes
        n_mds = nRounds * t * t  # MDS multiplications
        n_mds_sum = nRounds * t * 2  # MDS additions (2 per output per round)
        n_ark = nRounds * t  # Round constant additions
        n_rc = nRounds * t  # Round constant assignments
        n_mds_const = t * t  # MDS constant assignments
        n_init = t  # Initial state
        n_sbox_constraints = n_sbox * 3  # 3 multiplications per S-box

        total = n_sbox_constraints + n_mds + n_mds_sum + n_ark + n_rc + n_mds_const + n_init
        print(f"  Estimated constraints: ~{total}")
        print(f"    S-boxes: {n_sbox} × 3 = {n_sbox_constraints}")
        print(f"    MDS muls: {n_mds}")
        print(f"    MDS sums: {n_mds_sum}")
        print(f"    Round constant adds: {n_ark}")
        print(f"    Round constant assigns: {n_rc}")
        print(f"    MDS constant assigns: {n_mds_const}")
    else:
        print(content)

    return content


if __name__ == '__main__':
    t = 3
    Rf = 8
    Rp = 57

    outfile = sys.argv[1] if len(sys.argv) > 1 else None
    generate_circom(t, Rf, Rp, outfile)
